development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:2c0e59e783cce060223a73e2a53691b3@sole.redistogo.com:9665/
  channel_prefix: jabber_api_production
